config/routes.rb
Rails.application.routes.draw do

  root "web/welcome#index"

  scope module: :web do
    resources :users, only: [:new, :create] do
      member do
        get :confirm
      end
    end
    resource :session, only: [:new, :create, :destroy]
    resources :invites, only: [:create], param: :token do
      member do
        get :accept
      end
    end
  end

end

app/models/invite.rb
class Invite < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true, email: true
  validates :token, presence: true, uniqueness: true

  has_many :attempts, dependent: :destroy

  after_initialize :generate_token

  state_machine :state, initial: :not_accepted do
    state :accepted
    state :not_accepted

    event :accept do
      transition not_accepted: :accepted
    end
  end

  include InviteRepository

  def new_attempt
    if attempts.empty? || Time.now - attempts.last.created_at > configus.invites.period
      attempts.create
    else
      errors.add(:attempts, :too_often)
      false
    end
  end

  def to_param
    token
  end

  private

  def generate_token
    self.token ||= SecureHelper.generate_token
  end
end

app/models/invite/attempt.rb
class Invite::Attempt < ActiveRecord::Base
  belongs_to :invite
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password validations: false

  belongs_to :invite

  validates :email, presence: true, uniqueness: true, email: true
  validates :confirmation_token, uniqueness: true, allow_nil: true

  state_machine :state, initial: :unconfirmed do
    state :unconfirmed
    state :active

    event :confirm do
      transition unconfirmed: :active
    end
  end

  include UserRepository

  def guest?
    false
  end
end

app/models/user/guest.rb
class User::Guest
  def guest?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Concerns::AuthManagement
  include Concerns::FlashHelper

  helper_method :signed_in?, :current_user
end

app/controllers/concerns/auth_management.rb
module Concerns
  module AuthManagement
    def sign_in(user)
      session[:user_id] = user.id
    end

    def sign_out
      session[:user_id] = nil
    end

    def signed_in?
      !current_user.guest?
    end

    def authenticate_user!
      redirect_to new_session_path unless signed_in?
    end

    def current_user
      @current_user ||= (User.find_by(id: session[:user_id]) || User::Guest.new)
    end
  end
end

app/controllers/concerns/flash_helper.rb
module Concerns
  module FlashHelper
    def f(key, options = {} )
      scope = [:flash]
      scope << params[:controller].split('/')
      scope << params[:action]

      msg = options[:messages] || I18n.t(key, scope: scope)
      Rails.logger.debug("flash: #{msg}")
      if options[:now]
        flash.now[key] = msg
      else
        flash[key] = msg
      end
    end
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/web/invites_controller.rb
class Web::InvitesController < Web::ApplicationController
  skip_before_filter :authenticate_user!, only: [:accept]

  def create
    @invite_form = InviteForm.new(params[:invite_form])
    if @invite_form.valid?
      service = InvitationsService.new(@invite_form.email)
      if service.invite_user
        f(:success)
      else
        f(:error, messages: service.errors.full_messages)
      end
    else
      f(:error, messages: @invite_form.errors.full_messages)
    end

    redirect_to root_path
  end

  def accept
    @invite = Invite.not_accepted.find_by!(token: params[:token])
    session[:invite_id] = @invite.id
    redirect_to new_user_path
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < ApplicationController
  def new
    @signin_form = SigninForm.new
    if signed_in?
      redirect_to root_path
    else
      render :new
    end
  end

  def create
    @signin_form = SigninForm.new(params[:signin_form])

    if @signin_form.valid?
      sign_in(@signin_form.user)
      redirect_to root_path
    else
      render :new
    end

  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/web/users_controller.rb
class Web::UsersController < ApplicationController

  def new
    @signup_form = SignupForm.new
    @signup_form.email = current_invite.email if current_invite
  end

  def create
    @signup_form = SignupForm.new(params[:user])
    if @signup_form.save
      UserRegistrationService.new(@signup_form, current_invite).register
      f(:notice)
      redirect_to new_user_path
    else
      render :new
    end
  end

  def confirm
    @user = User.find_by!(id: params[:id], confirmation_token: params[:confirmation_token])
    if UserRegistrationService.new(@user).confirm
      sign_in(@user)
    else
      f(:error)
    end
    redirect_to root_path
  end

  private
  def current_invite
    @current_invite ||= Invite.not_accepted.find_by(id: session[:invite_id])
  end

end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index
    @invite = InviteForm.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web/welcome_helper.rb
module Web::WelcomeHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Testapp"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#")= t('.kitty')
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav.pull-right
            %li= link_to t('.logout'), session_path, method: :delete

    .container.content
      .row
        .col-sm-8.col-sm-offset-2
          = bootstrap_flash
          = yield
      %footer
        %p &copy; Company 2015

app/views/web/invites/accept.html.haml
= simple_form_for @signup_form, url: users_path, method: :post, html: {class: 'form-horizontal'} do |f|
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  .pull-right
    = link_to t('.login'), new_session_path, class: 'btn btn-default'
    = f.button :submit, class: 'btn-primary'

app/views/web/users/new.html.haml
= simple_form_for @signup_form, url: users_path, method: :post, html: {class: 'form-horizontal'} do |f|
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  .pull-right
    = link_to t('.login'), new_session_path, class: 'btn btn-default'
    = f.button :submit, class: 'btn-primary'

app/views/web/welcome/_invite_form.html.haml
= simple_form_for @invite, url: invites_path, method: :post, html: {class: "form-horizontal"} do |f|
  = f.label "Invite your friends"
  = f.input :email, placeholder: "Email", label: false
  = f.button :submit

app/views/web/welcome/index.html.haml
.col-sm-6
  = image_tag 'kitty.jpg', width: "100%"
.col-sm-6
  = render 'invite_form'